//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTTCS_64130531.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sanpham()
        {
            this.Chitietsanpham = new HashSet<Chitietsanpham>();
            this.Review = new HashSet<Review>();
        }
    
        public string maSanpham { get; set; }
        public string tenSanpham { get; set; }
        public string moTa { get; set; }
        public int soLuongyeuthich { get; set; }
        public int Mahdh { get; set; }
        public int Mahang { get; set; }
        public string maKhuyenmai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietsanpham> Chitietsanpham { get; set; }
        public virtual Hangsanxuat Hangsanxuat { get; set; }
        public virtual Hedieuhanh Hedieuhanh { get; set; }
        public virtual Khuyenmai Khuyenmai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Review { get; set; }
    }
}
