//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_64130531.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitietsanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chitietsanpham()
        {
            this.Chitiethoadon = new HashSet<Chitiethoadon>();
        }
    
        public string id_chitietSP { get; set; }
        public string hinhAnh { get; set; }
        public int soLuongTon { get; set; }
        public Nullable<decimal> gia { get; set; }
        public int maMau { get; set; }
        public string maSanpham { get; set; }
        public int maSize { get; set; }
        public string tenMau { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Sanpham Sanpham { get; set; }
        public virtual Size Size { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitiethoadon> Chitiethoadon { get; set; }
    }
}
