//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT0720PhamDucHai_64130531.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SinhVien
    {
        [Required(ErrorMessage = "Chưa nhập mã sinh viên")]
        public string MaSV { get; set; }
        [Required(ErrorMessage = "Chưa nhập họ sinh viên")]
        public string HoSV { get; set; }
        [Required(ErrorMessage = "Chưa nhập tên sinh viên")]
        public string TenSV { get; set; }
        [Required(ErrorMessage = "Chưa nhập ngày sinh")]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Required(ErrorMessage = "Chưa chọn giới tính")]
        public Nullable<bool> GioiTinh { get; set; }
        [Required(ErrorMessage = "Chưa chọn ảnh sinh viên")]
        public string AnhSV { get; set; }
        [Required(ErrorMessage = "Chưa nhập địa chỉ")]
        public string DiaChi { get; set; }
        [Required(ErrorMessage = "Chưa chọn mã lớp")]
        public string MaLop { get; set; }
    
        public virtual LOP LOP { get; set; }
    }
}
