//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCK_64130531.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitiethoadon
    {
        public string id_chitietHD { get; set; }
        public string maHoadon { get; set; }
        public string id_chitietSP { get; set; }
        public int soLuong { get; set; }
        public Nullable<int> trangThai { get; set; }
    
        public virtual Chitietsanpham Chitietsanpham { get; set; }
        public virtual Sanpham Sanpham { get; set; }
        public virtual Hoadon Hoadon { get; set; }
    }
}
