//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCK_64130531.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public string maComment { get; set; }
        public string noiDung { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public string ma_cmCha { get; set; }
        public string taikhoan { get; set; }
        public string maBlog { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual Users Users { get; set; }
    }
}
