//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCK_64130531.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public string maReview { get; set; }
        public string noiDung { get; set; }
        public Nullable<System.DateTime> ngayNhap { get; set; }
        public int soSao { get; set; }
        public string taikhoan { get; set; }
        public string maSanpham { get; set; }
    
        public virtual Sanpham Sanpham { get; set; }
        public virtual Users Users { get; set; }
    }
}
